package protocol

import (
	"bytes"
	"encoding/hex"
	"encoding/json"
	"flag"
	"os"
	"reflect"
	"strings"
	"testing"
)

var update = flag.Bool("update", false, "rewrite testdata/vectors.json")

type envVector struct {
	AAD       string `json:"aad"`
	Nonce     string `json:"nonce_hex"`
	Plaintext string `json:"plaintext"`
	Envelope  string `json:"envelope"`
}

type vectors struct {
	Comment   string      `json:"comment"`
	PSK       string      `json:"psk_hex"`
	EncKey    string      `json:"enc_key_hex"`
	ReqTopic  string      `json:"req_topic"`
	RespTopic string      `json:"resp_topic"`
	Envelopes []envVector `json:"envelopes"`
	// Envelopes that must be dropped (wrong AAD, tampered, malformed).
	Reject  []envVector `json:"reject"`
	Pairing struct {
		String  string  `json:"string"`
		Decoded Pairing `json:"decoded"`
	} `json:"pairing"`
}

func fixedPSK() []byte {
	psk := make([]byte, 32)
	for i := range psk {
		psk[i] = byte(i)
	}
	return psk
}

func buildVectors(t *testing.T) vectors {
	t.Helper()
	psk := fixedPSK()
	k, err := Derive(psk)
	if err != nil {
		t.Fatal(err)
	}
	v := vectors{
		Comment:   "Generated by `go test ./internal/protocol -update`. Checked by android/core ProtocolTest.",
		PSK:       hex.EncodeToString(psk),
		EncKey:    hex.EncodeToString(k.EncKey),
		ReqTopic:  k.ReqTopic,
		RespTopic: k.RespTopic,
	}
	req, _ := json.Marshal(Request{
		ID: "AAECAwQFBgcICQoLDA0ODw", TS: 1790000000, Label: "mgmt-1", Who: "claude@mgmt-1",
		PubKey:     "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAECAwQFBgcICQoLDA0ODxAREhMUFRYXGBkaGxwdHh8g",
		Principals: []string{"root"}, TTL: 14400,
	})
	resp, _ := json.Marshal(Response{ID: "AAECAwQFBgcICQoLDA0ODw", TS: 1790000042, Status: StatusDenied})
	add := func(aad string, pt []byte, nonceByte byte) envVector {
		nonce := bytes.Repeat([]byte{nonceByte}, 12)
		env, err := Seal(k.EncKey, aad, pt, nonce)
		if err != nil {
			t.Fatal(err)
		}
		return envVector{AAD: aad, Nonce: hex.EncodeToString(nonce), Plaintext: string(pt), Envelope: string(env)}
	}
	v.Envelopes = []envVector{
		add(AADRequest, req, 0x11),
		add(AADResponse, resp, 0x22),
		add(AADResponse, []byte(`{"unicode":"✓ ü"}`), 0x33),
	}

	good := v.Envelopes[0]
	var e Envelope
	_ = json.Unmarshal([]byte(good.Envelope), &e)
	ct, _ := b64url.DecodeString(e.C)
	ct[0] ^= 1
	tampered, _ := json.Marshal(Envelope{V: 1, N: e.N, C: b64url.EncodeToString(ct)})
	badV, _ := json.Marshal(Envelope{V: 2, N: e.N, C: e.C})
	v.Reject = []envVector{
		{AAD: AADResponse, Envelope: good.Envelope}, // request envelope replayed as a response
		{AAD: AADRequest, Envelope: string(tampered)},
		{AAD: AADRequest, Envelope: string(badV)},
		{AAD: AADRequest, Envelope: `{"v":1,"n":"short","c":"AAAA"}`},
		{AAD: AADRequest, Envelope: `not json`},
		{AAD: AADRequest, Envelope: `{"v":1,"n":"ERERERERERERERER","c":"!!"}`},
	}

	v.Pairing.Decoded = Pairing{
		V: 1, Ntfy: "https://ntfy.sh", PWA: "https://yessh.example/",
		PSK: b64url.EncodeToString(psk),
		CA:  "ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBFakeFakeFake yessh-ca",
	}
	v.Pairing.String, err = EncodePairing(v.Pairing.Decoded)
	if err != nil {
		t.Fatal(err)
	}
	return v
}

func TestVectors(t *testing.T) {
	got := buildVectors(t)
	path := "testdata/vectors.json"
	if *update {
		b, _ := json.MarshalIndent(got, "", "  ")
		if err := os.WriteFile(path, append(b, '\n'), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	raw, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	var want vectors
	if err := json.Unmarshal(raw, &want); err != nil {
		t.Fatal(err)
	}
	if !reflect.DeepEqual(got, want) {
		t.Fatalf("vectors drifted; run with -update if intentional")
	}

	key, _ := hex.DecodeString(want.EncKey)
	for i, ev := range want.Envelopes {
		pt, err := Open(key, ev.AAD, []byte(ev.Envelope))
		if err != nil || string(pt) != ev.Plaintext {
			t.Errorf("envelope %d: open = %q, %v", i, pt, err)
		}
	}
	for i, ev := range want.Reject {
		if _, err := Open(key, ev.AAD, []byte(ev.Envelope)); err != ErrDrop {
			t.Errorf("reject %d: got %v, want ErrDrop", i, err)
		}
	}
	p, err := ParsePairing(want.Pairing.String)
	if err != nil || p != want.Pairing.Decoded {
		t.Errorf("pairing: %+v %v", p, err)
	}
}

func TestTopicShape(t *testing.T) {
	k, _ := Derive(fixedPSK())
	for _, topic := range []string{k.ReqTopic, k.RespTopic} {
		if len(topic) != len("yessh-r-")+32 || strings.ToLower(topic) != topic || strings.Contains(topic, "=") {
			t.Errorf("bad topic %q", topic)
		}
	}
	if k.ReqTopic == k.RespTopic {
		t.Error("topics must differ")
	}
	if _, err := Derive(make([]byte, 31)); err == nil {
		t.Error("short psk accepted")
	}
}

func TestSealOpenRandomNonce(t *testing.T) {
	k, _ := Derive(fixedPSK())
	a, _ := Seal(k.EncKey, AADRequest, []byte("hi"), nil)
	b, _ := Seal(k.EncKey, AADRequest, []byte("hi"), nil)
	if bytes.Equal(a, b) {
		t.Fatal("nonce reuse")
	}
	other, _ := Derive(bytes.Repeat([]byte{9}, 32))
	if _, err := Open(other.EncKey, AADRequest, a); err != ErrDrop {
		t.Fatal("wrong key accepted")
	}
}

func TestParsePairingErrors(t *testing.T) {
	good := buildVectors(t).Pairing.Decoded
	for name, mut := range map[string]func(p *Pairing){
		"version": func(p *Pairing) { p.V = 2 },
		"ntfy":    func(p *Pairing) { p.Ntfy = "ftp://x" },
		"ca":      func(p *Pairing) { p.CA = "ssh-ed25519 AAAA" },
		"psk":     func(p *Pairing) { p.PSK = "AAAA" },
	} {
		p := good
		mut(&p)
		s, _ := EncodePairing(p)
		if _, err := ParsePairing(s); err == nil {
			t.Errorf("%s: accepted", name)
		}
	}
	if _, err := ParsePairing("nope"); err == nil {
		t.Error("missing prefix accepted")
	}
	// Standard base64 PSK with padding is accepted too.
	p := good
	p.PSK = "AAECAwQFBgcICQoLDA0ODxAREhMUFRYXGBkaGxwdHh8="
	s, _ := EncodePairing(p)
	if _, err := ParsePairing(s); err != nil {
		t.Errorf("std base64 psk: %v", err)
	}
	if !ValidLabel("mgmt-1") || ValidLabel("a:b") || ValidLabel("") {
		t.Error("ValidLabel")
	}
}
